name = "firesolid"
uuid = "8835567d-bc69-4eab-930a-4966f2f7dae8"
authors = ["Chris de Graaf", "Invenia Technical Computing Corporation"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
